apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: "{{ .Release.Namespace }}"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sealed-secrets
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    chart: sealed-secrets
    repoURL: oci://registry-1.docker.io/bitnamicharts/sealed-secrets
    targetRevision: 2.19.0
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
