apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: "{{ .Release.Namespace }}"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: traefik
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    chart: traefik
    repoURL: oci://ghcr.io/traefik/helm/traefik
    targetRevision: 41.0.0
    helm:
      valuesObject:
        providers:
          kubernetesGateway:
            enabled: true
        service:
          spec:
            type: NodePort
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
