- name: Assert distribution is supported
  ansible.builtin.assert:
    that: ansible_facts['distribution'] in ['Debian']
    fail_msg: "{{ ansible_facts['distribution'] }} is not a supported distro for this role. Supported distros: Debian"

- name: Include tasks for Powertop
  ansible.builtin.include_tasks: powertop.yml

- name: Include tasks for AutoASPM
  ansible.builtin.include_tasks: autoaspm.yml
