argument_specs:
  main:
    short_description: Automatically install updates
    options:
      # === OPTIONAL ===
      jwau_autoupdate_reboot_time:
        type: str
        required: false
        description: Approximately time to update in format "hh:mm".
