- name: Assert distribution is supported
  ansible.builtin.assert:
    that: ansible_facts['distribution'] in ['Debian']
    fail_msg: "{{ ansible_facts['distribution'] }} is not a supported distro for this role. Supported distros: Debian"

- name: Include basic tasks
  ansible.builtin.include_tasks: basics.yml

- name: Include tasks for smtp-cli
  ansible.builtin.include_tasks: smtp_cli.yml
