- name: Assert distribution is supported
  ansible.builtin.assert:
    that: ansible_facts['distribution'] in ['Debian']
    fail_msg: "{{ ansible_facts['distribution'] }} is not a supported distro for this role. Supported distros: Debian"

- name: Install Wireguard
  ansible.builtin.include_tasks: install.yml

- name: Configure Wireguard
  ansible.builtin.include_tasks: configure.yml
  vars:
    wg_config: "{{ item }}"
  loop: "{{ jwwg_wireguard_interfaces }}"

- name: Remove orphaned interfaces
  ansible.builtin.include_tasks: remove_orphans.yml
