argument_specs:
  main:
    short_description: Setup network config
    options:
      # === OPTIONAL ===
      jwnetconf_dhcp_fallback_prefixes:
        type: list
        elements: str
      jwnetconf_interfaces:
        type: list
        elements: dict
        required: true
        required_if:
          - ["type", "static", ["cidr_address"]]
        options:
          name:
            type: str
            required: true
            description: Name of the interface
          name_is_wildcard_prefix:
            type: bool
            required: false
            description: When set, a wildcard will be appended after the name
          priority:
            type: int
            required: true
            description: The priority of the network config. First matching config is used.
          type:
            type: str
            required: true
            choices:
              - dhcp
              - static
              - none
          cidr_address:
            type: str
            # required: See "required_if"
          vlans:
            type: dict
            required: false
            description: >-
              Map of VLAN id to a dict with key "suffix". For each VLAN, a VLAN interface and a
              bridge on top of it are created, and a "VLAN=" entry is added to this interface.
              e.g. {11: {"suffix": "wifi"}}
      jwnetconf_override_dns:
        type: list
        elements: str
        required: false
        description: Use these DNS IP's instead of the DHCP provided ones
