apiVersion: 1
groups:
  - orgId: 1
    name: Deprecated
    folder: Logs
    interval: 24h
    rules:
      - uid: ar_logs_deprecated
        title: Deprecated
        condition: C
        data:
          - refId: A
            queryType: range
            relativeTimeRange:
              from: 86400
              to: 0
            datasourceUid: ds_loki_main
            model:
              editorMode: code
              expr: |
                # Exclude all logs from Loki and Grafana as they often include below query, resulting to false positives
                sum(count_over_time({host=~".+",container_name!="loki",container_name!="grafana"}
                # Select all logs containing "deprecat" case-insensitive
                |~ "(?i)deprecat"

                # General ignores
                != "(Use `node --trace-deprecation ...` to show where the warning was created)"

                # Related to Unifi Network App
                != "WARNING: A terminally deprecated method in sun.misc.Unsafe has been called"

                # Related to WikiJS
                != "[DEP0174] DeprecationWarning: Calling promisify on a function that returns a Promise is likely a mistake."
                != "[DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead."

                # Related to xfs_scrub_all
                != "DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC)."

                # DELETE ME: Fixed, but included to prevent re-reports:
                != "pam_env(sshd:session): deprecated reading of user environment enabled"
                != "NEKO_WEBRTC_NAT1TO1"
                [24h]))
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              queryType: range
              refId: A
          - refId: reducer
            queryType: expression
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params: []
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                name: Expression
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: last
              refId: reducer
              type: reduce
          - refId: C
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: reducer
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: OK
        execErrState: Error
        for: 0s
        annotations: {}
        labels: {}
        isPaused: false
        notification_settings:
          receiver: grafana-default-email
          repeat_interval: 24h
