- name: Validate args
  ansible.builtin.validate_argument_spec:
    argument_spec:
      # === REQUIRED ===
      jwnu_nut_type:
        type: str
        required: true
        choices:
          - client_only
          - client_server
        description: Type of NUT install

      jwnu_nut_users:
        type: dict
        required: false
        description: Dictionary of NUT users with password, upsmon role, and actions. See https://networkupstools.org/docs/man/upsd.users.html for details.
        suboptions:
          password:
            type: str
            required: true
            description: Password for the NUT user
          upsmon:
            type: str
            required: true
            description: upsmon role (e.g. primary)
          actions:
            type: list
            elements: str
            required: false
            description: List of allowed upsmon actions (e.g., SET, FSD)

      # === CONDITIONAL OPTIONAL ===
      jwnu_nut_server_ip:
        type: str
        required: "{{ jwnu_nut_type == 'client_only' }}"

      jwnu_ups_vendor_id:
        type: str
        required: "{{ jwnu_nut_type == 'client_server' }}"

      jwnu_ups_product_id:
        type: str
        required: "{{ jwnu_nut_type == 'client_server' }}"

      jwnu_ups_serial:
        type: str
        required: "{{ jwnu_nut_type == 'client_server' }}"
