# Based on https://wiki.debian.org/SystemdNetworkd

- name: Assert distribution is supported
  ansible.builtin.assert:
    that: ansible_facts['distribution'] in ['Debian']
    fail_msg: "{{ ansible_facts['distribution'] }} is not a supported distro for this role. Supported distros: Debian"

- name: Setup network interfaces
  become: true
  block:
    - name: Enrich network configs
      ansible.builtin.set_fact:
        jwnetconf_enriched: "{{ jwnetconf_interfaces | netconfig_enrich(jwnetconf_dhcp_fallback_prefixes) }}"
        jwnetconf_vlans_enriched: "{{ jwnetconf_interfaces | netconfig_enrich_vlans }}"

    - name: Expected network configs
      ansible.builtin.debug:
        var: jwnetconf_enriched

    - name: Expected VLAN configs
      ansible.builtin.debug:
        var: jwnetconf_vlans_enriched

    - name: Drop ifupdown configs
      ansible.builtin.file:
        path: "/etc/network/{{ item }}"
        state: absent
      loop:
        - interfaces
        - interfaces.d
      notify:
        - Initramfs regenerate
        - Reboot

    - name: Enable systemd-networkd
      ansible.builtin.systemd_service:
        name: systemd-networkd
        enabled: true
      notify:
        - Initramfs regenerate
        - Reboot

    - name: Create network configs
      ansible.builtin.template:
        src: interface.network
        dest: "/etc/systemd/network/{{ item.filename }}"
        owner: root
        group: root
        mode: "0644"
      loop: "{{ jwnetconf_enriched }}"
      notify:
        - Initramfs regenerate
        - Restart systemd-networkd

    - name: Create VLAN netdev configs
      ansible.builtin.template:
        src: vlan.netdev
        dest: "/etc/systemd/network/{{ item.vlan_netdev_filename }}"
        owner: root
        group: root
        mode: "0644"
      loop: "{{ jwnetconf_vlans_enriched }}"
      notify:
        - Initramfs regenerate
        - Restart systemd-networkd

    - name: Create VLAN network configs
      ansible.builtin.template:
        src: vlan.network
        dest: "/etc/systemd/network/{{ item.vlan_network_filename }}"
        owner: root
        group: root
        mode: "0644"
      loop: "{{ jwnetconf_vlans_enriched }}"
      notify:
        - Initramfs regenerate
        - Restart systemd-networkd

    - name: Create VLAN bridge netdev configs
      ansible.builtin.template:
        src: bridge.netdev
        dest: "/etc/systemd/network/{{ item.bridge_netdev_filename }}"
        owner: root
        group: root
        mode: "0644"
      loop: "{{ jwnetconf_vlans_enriched }}"
      notify:
        - Initramfs regenerate
        - Restart systemd-networkd

    - name: Create VLAN bridge network configs
      ansible.builtin.template:
        src: bridge.network
        dest: "/etc/systemd/network/{{ item.bridge_network_filename }}"
        owner: root
        group: root
        mode: "0644"
      loop: "{{ jwnetconf_vlans_enriched }}"
      notify:
        - Initramfs regenerate
        - Restart systemd-networkd

    - name: Find orphaned interfaces
      ansible.builtin.find:
        paths: /etc/systemd/network/
        file_type: file
        excludes: >-
          {{
            (jwnetconf_enriched | map(attribute='filename') | list)
            + (jwnetconf_vlans_enriched | map(attribute='vlan_netdev_filename') | list)
            + (jwnetconf_vlans_enriched | map(attribute='vlan_network_filename') | list)
            + (jwnetconf_vlans_enriched | map(attribute='bridge_netdev_filename') | list)
            + (jwnetconf_vlans_enriched | map(attribute='bridge_network_filename') | list)
          }}
      register: orphaned_interfaces

    - name: Remove orphaned interfaces
      ansible.builtin.file:
        name: "{{ item }}"
        state: absent
      loop: "{{ orphaned_interfaces['files'] | map(attribute='path') }}"
      notify:
        - Initramfs regenerate
        - Restart systemd-networkd

- name: Configure DNS
  ansible.builtin.include_tasks: dns.yml

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
