argument_specs:
  main:
    short_description: Configure observability agent(s)
    options:
      # === REQUIRED ===
      jwob_with_docker:
        description: Enable logging and monitoring of Docker containers
        required: true
        type: bool
