- name: Assert distribution is supported
  ansible.builtin.assert:
    that: ansible_facts['distribution'] in ['Debian']
    fail_msg: "{{ ansible_facts['distribution'] }} is not a supported distro for this role. Supported distros: Debian"

- name: VM host
  become: true
  block:
    - name: "Include tasks for {{ subtask }}"
      ansible.builtin.include_tasks: "{{ subtask | lower }}.yml"
      loop_control:
        loop_var: subtask
      loop:
        - Libvirt
        - Cockpit
        - Caddy
