#!/bin/sh

send_email () {
    . /opt/smtp-cli/smtp-cli.conf # /bin/sh doesn't support "source"
    echo "${2:?}" | /opt/smtp-cli/smtp-cli \
        --from-name "${FROM_NAME:?}" \
        --from-address "${FROM_EMAIL:?}" \
        --to-name "${TO_NAME:?}" \
        --to-address "${TO_EMAIL:?}" \
        --host "in-v3.mailjet.com" \
        --username "${USERNAME:?}" \
        --password "${PASSWORD:?}" \
        --subject "${1:?}"
}

BATTERY_LEVEL=$(upsc apc battery.charge)
STATUS=$(upsc apc ups.status)
MSG_SUFFIX="\n\nINFO:\n- level: ${BATTERY_LEVEL:-Unknown}/100\n- status: ${STATUS:-Unknown}"

SUBJECT=""
MSG=""

case $1 in
onbatt)
    SUBJECT="UPS running on battery"
    MSG="UPS is running on battery since 60 seconds."
    ;;
online)
    SUBJECT="UPS power restored"
    MSG="UPS is running on mains again."
    ;;
commbad)
    SUBJECT="UPS connection broken"
    MSG="Unable to contact UPS since 60 seconds."
    ;;
commok)
    SUBJECT="UPS connection restored"
    MSG="Contact with UPS has been restored."
    ;;
lowbatt)
    SUBJECT="UPS BATTERY CRITICAL"
    MSG="Battery level of UPS is critically low!"
    ;;
fsd)
    SUBJECT="UPS FSD FLAG SET"
    MSG="FSD flag has been set. Preparing for shutdown ..."
    ;;
shutdown)
    SUBJECT="UPS SHUTDOWN"
    MSG="Host is shutting down due to UPS."
    ;;
replbatt)
    SUBJECT="Replace UPS battery"
    MSG="The battery of the UPS should be replaced."
    ;;
nocomm)
    SUBJECT="Unable to contact UPS"
    MSG="The UPS cannot be contacted for monitoring."
    ;;
noparent)
    SUBJECT="upsmon parent process crashed"
    MSG="The upsmon parent process crashed. Shutdown is impossible!"
    ;;
*)
    SUBJECT="Unknown UPS command received"
    MSG="I received an unknown UPS command: $1."
    ;;
esac

send_email "${SUBJECT:?}" "${MSG:?} ${MSG_SUFFIX:?}"
