#!/bin/sh

send_email () {
    . /opt/smtp-cli/smtp-cli.conf # /bin/sh doesn't support "source"
    echo "${2:?}" | /opt/smtp-cli/smtp-cli \
        --from-name "${FROM_NAME:?}" \
        --from-address "${FROM_EMAIL:?}" \
        --to-name "${TO_NAME:?}" \
        --to-address "${TO_EMAIL:?}" \
        --host "in-v3.mailjet.com" \
        --username "${USERNAME:?}" \
        --password "${PASSWORD:?}" \
        --subject "${1:?}"
}

case $1 in
onbatt)
    send_email "UPS running on battery" "UPS is running on battery since 60 seconds."
    ;;
online)
    send_email  "UPS power restored" "UPS is running on mains again."
    ;;
commbad)
    send_email  "UPS connection broken" "Unable to contact UPS since 60 seconds."
    ;;
commok)
    send_email  "UPS connection restored" "Contact with UPS has been restored."
    ;;
lowbatt)
    send_email  "UPS BATTERY CRITICAL" "Battery level of UPS is critically low. Setting FSD flag ..."
    /usr/sbin/upsmon -c fsd
    ;;
fsd)
    send_email  "UPS FSD FLAG SET" "FSD flag has been set. Preparing for shutdown ..."
    ;;
shutdown)
    send_email  "UPS SHUTDOWN" "Host is shutting down due to UPS."
    ;;
replbatt)
    send_email  "Replace UPS battery" "The battery of the UPS should be replaced."
    ;;
nocomm)
    send_email  "Unable to contact UPS" "The UPS cannot be contacted for monitoring."
    ;;
noparent)
    send_email  "upsmon parent process crashed" "The upsmon parent process crashed. Shutdown is impossible!"
    ;;
*)
    send_email  "Unknown UPS command received" "I received an unknown UPS command: $1."
    ;;
esac
